<?php
/**
 * Created by PhpStorm.
 * User: Pedram
 * Date: 21/11/2017
 * Time: 09:04 PM
 */
namespace backend\components;


use Yii;


class Controller extends \yii\web\Controller
{
    public function init()
    {
        parent::init();
        if(!Yii::$app->user->can('admin')){
        return $this->redirect('http://localhost:8080/gallery/');
        }
       // TODO: Change the autogenerated stub

    }





}